### ISSUE TITLE
Charge of the Righteous

### ISSUE THREAD

**Issue by knk101** [Envibel/MartialExcellence#3]
https://www.d20pfsrd.com/feats/combat-feats/charge-of-the-righteous-combat

Super thematic :)

**Comment by Envibel** [comment]
Thank you for your suggestions! I'm going to move these over to the suggestions thread and close these individual ones out. If you'd like to submit anymore suggestions please do so in the suggestions thread :) https://github.com/Envibel/MartialExcellence/issues/1
