### ISSUE TITLE
Request Slayer Archetype - Grave Warden

### ISSUE THREAD

**Issue by Ner013** [Envibel/MartialExcellence#5]
Is there any chance you’ll add the slayer archetype Grave Warden from Call of the Wild mod in Kingmaker in a future update?

**Comment by Envibel** [comment]
I'd say never say never but given that there is a large focus on demons in wotr and not a terrible amount of undead I'd say it is unfortunately unlikely. Also, I'll be closing this issue and and leaving a comment with your suggestions in the suggestions thread just to keep all suggestions consolidated. If you have more suggestions please leave them there as well.

https://github.com/Envibel/MartialExcellence/issues/1
